using Npgsql;
using Testcontainers.PostgreSql;

namespace claude_starter.IntegrationTests.Infrastructure;

/// <summary>
/// One Postgres container for the whole assembly. Collections each carve their
/// own database out of it, which is what lets them run in parallel; starting a
/// container per collection would cost more than the parallelism buys.
/// </summary>
public sealed class ContainerFixture : IAsyncLifetime
{
    private readonly PostgreSqlContainer _container = new PostgreSqlBuilder("postgres:16")
        .WithDatabase("postgres")
        .WithUsername("postgres")
        .WithPassword("postgres")
        .Build();

    // Postgres needs exclusive access to the template database while cloning it,
    // so concurrent CREATE DATABASE calls fail. Collections start in parallel,
    // so their database creation is serialised here.
    private readonly SemaphoreSlim _createGate = new(1, 1);

    public async ValueTask InitializeAsync() => await _container.StartAsync();

    public async ValueTask DisposeAsync() => await _container.DisposeAsync();

    /// <summary>
    /// Creates a database and hands back a connection string pointing at it.
    /// </summary>
    public async Task<string> CreateDatabaseAsync(string name)
    {
        {
            await using var admin = new NpgsqlConnection(_container.GetConnectionString());
            await admin.OpenAsync();
            await using var cmd = admin.CreateCommand();
            // The name is generated by the caller, never taken from test input.
            cmd.CommandText = $"CREATE DATABASE \"{name}\"";
            await cmd.ExecuteNonQueryAsync();
        }

        return new NpgsqlConnectionStringBuilder(_container.GetConnectionString())
        {
            Database = name,
        }.ConnectionString;
    }
}
